spring:
    profiles:
        active:
            - dev
---
spring:
    profiles: dev
    application:
        name: microservice-config-sjl-dev
---
spring:
    profiles: test
    application:
        name: microservice-config-sjl-test
#请保存为UTF-8格式